### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ssssweibin**
維斌的Sec2 Part1 作業  :  Response of JSONIFY data ready  and page4 query succeed
URL :  http://34.231.207.168:3000/api/attractions?page=1&keyword=紀念
URL :  http://34.231.207.168:3000/api/attraction/12

### CODE REVIEW

**Comment by cwpeng** [comment]
1. "images" field should be an array containing image URLs separately, not a string.
2. "nextPage" means current page plus 1. So, "nextPage" of http://34.231.207.168:3000/api/attractions?page=0 should be 1, and so on.

**Comment by ssssweibin** [comment]
Resent Pull request

**Comment by ssssweibin** [comment]
Correction of image format and nextPage
URL :  http://34.231.207.168:3000/api/attractions?page=2&keyword=紀念
URL :  http://34.231.207.168:3000/api/attraction/12

**Comment by cwpeng** [comment]
Your server is down for now.

**Pull request closed without merging**
